In [1]:
import os
import csv
import pandas as pd
import numpy as np

In [8]:
# data file's path:
hospital_data = "Hospital_Summary_Ratings_By_CITY_STATE_For_Upload_SORTED.csv"

In [9]:
# Use Pandas to read data
hospital_data = pd.read_csv(hospital_data)
hospital_data.head()

,City,State,Provider ID,Hospital Name,County Name,HCAHPS Question Type,Patient Survey Star Rating (out of 5),Number of Completed Surveys,Survey Response Rate Percent,Measure Start Date,Measure End Date,Unnamed: 11,Unnamed: 12
0,ANCHORAGE,AK,20026,ALASKA NATIVE MEDICAL CENTER,ANCHORAGE,Summary star rating,3,731,13,4/1/2016,3/31/2017,NaN,NaN
1,ANCHORAGE,AK,20017,ALASKA REGIONAL HOSPITAL,ANCHORAGE,Summary star rating,3,816,15,4/1/2016,3/31/2017,NaN,NaN
2,ANCHORAGE,AK,20001,PROVIDENCE ALASKA MEDICAL CENTER,ANCHORAGE,Summary star rating,3,1797,20,4/1/2016,3/31/2017,NaN,NaN
3,BETHEL,AK,20018,YUKON KUSKOKWIM DELTA REG HOSPITAL,BETHEL,Summary star rating,2,260,27,4/1/2016,3/31/2017,NaN,NaN
4,FAIRBANKS,AK,20012,FAIRBANKS MEMORIAL HOSPITAL,FAIRBANKS NORTH STAR,Summary star rating,4,642,23,4/1/2016,3/31/2017,NaN,NaN

In [10]:
hospital_reviews = "Total Hospital Review - Averages BY STATE.csv"

In [12]:
# Use Pandas to read data
hospital_reviews = pd.read_csv(hospital_reviews)
hospital_reviews.head()

  State  # Hospitals Sampled  Adams_State Wide Avg Review - (# stars out of 5)
0    AK                   12                                              2.75
1    AL                   83                                              2.95
2    AR                   64                                              2.79
3    AZ                   73                                              2.58
4    CA                  312                                              2.57